# Generated by Django 4.2 on 2024-12-07 14:48

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='locationAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sity', models.CharField(db_index=True, max_length=50)),
                ('sity_en', models.CharField(db_index=True, max_length=50, null=True)),
                ('sity_ru', models.CharField(db_index=True, max_length=50, null=True)),
                ('sity_hy', models.CharField(db_index=True, max_length=50, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('name_en', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('name_ru', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('name_hy', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
                ('sity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='street', to='location.locationavailable')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.BigIntegerField(blank=True, null=True)),
                ('adres', models.CharField(blank=True, max_length=70, null=True)),
                ('adres_en', models.CharField(blank=True, max_length=70, null=True)),
                ('adres_ru', models.CharField(blank=True, max_length=70, null=True)),
                ('adres_hy', models.CharField(blank=True, max_length=70, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('custumer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_adres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.CharField(blank=True, db_index=True, max_length=70, null=True)),
                ('district', models.FloatField(blank=True, null=True)),
                ('center_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('sity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='location.locationavailable')),
                ('stret', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='location.street')),
            ],
        ),
    ]
