# Generated by Django 4.2 on 2024-12-11 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddresses',
            name='createOrUpdateDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
