# Generated by Django 4.2 on 2024-02-19 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StreetSity',
        ),
    ]
