# Generated by Django 4.2 on 2024-02-20 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_streetsity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StreetSity',
        ),
    ]
