# Generated by Django 4.2 on 2024-02-20 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_building'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='area',
            new_name='geometry',
        ),
        migrations.RemoveField(
            model_name='building',
            name='center_point',
        ),
    ]
