# Generated by Django 4.2 on 2024-02-21 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_rename_area_building_geometry_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Building',
        ),
    ]
