# Generated by Django 4.2 on 2024-02-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='street',
            name='name_en',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='street',
            name='name_hy',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='street',
            name='name_ru',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
