# Generated by Django 4.2 on 2024-02-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0012_alter_street_name_alter_street_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='adres',
            field=models.CharField(db_index=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='locationavailable',
            name='sity',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='locationavailable',
            name='sity_en',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='locationavailable',
            name='sity_hy',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='locationavailable',
            name='sity_ru',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
    ]
