# Generated by Django 4.2 on 2024-02-26 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0013_alter_building_adres_alter_locationavailable_sity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='street',
            name='sity',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='Street',
        ),
    ]
