# Generated by Django 4.2 on 2024-12-07 14:48

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50, unique=True)),
                ('names_en', models.CharField(max_length=50, null=True, unique=True)),
                ('names_ru', models.CharField(max_length=50, null=True, unique=True)),
                ('names_hy', models.CharField(max_length=50, null=True, unique=True)),
                ('specialcolumn', models.CharField(blank=True, max_length=50, null=True)),
                ('specialcolumn_en', models.CharField(blank=True, max_length=50, null=True)),
                ('specialcolumn_ru', models.CharField(blank=True, max_length=50, null=True)),
                ('specialcolumn_hy', models.CharField(blank=True, max_length=50, null=True)),
                ('popularity', models.FloatField(default=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='grups_img')),
                ('startwork', models.TimeField(blank=True, null=True)),
                ('stopwork', models.TimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'ընկերություն',
                'verbose_name_plural': 'ընկերություններ',
            },
        ),
        migrations.CreateModel(
            name='ServisCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50)),
                ('names_en', models.CharField(max_length=50, null=True)),
                ('names_ru', models.CharField(max_length=50, null=True)),
                ('names_hy', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_img')),
            ],
            options={
                'verbose_name': 'ծառայության տեսակ',
                'verbose_name_plural': 'ծառայության տեսակներ',
            },
        ),
        migrations.CreateModel(
            name='PopularityCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gnahatakan', models.PositiveSmallIntegerField()),
                ('post', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='grups.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'կարծիք',
                'verbose_name_plural': 'կարծիքներ',
            },
        ),
        migrations.CreateModel(
            name='CompanyDiscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.TextField(blank=True, null=True)),
                ('discription_en', models.TextField(blank=True, null=True)),
                ('discription_ru', models.TextField(blank=True, null=True)),
                ('discription_hy', models.TextField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('tel', phone_field.models.PhoneField(blank=True, max_length=31, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grup', to='grups.company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cat_comp', to='grups.serviscategory'),
        ),
    ]
